### ISSUE TITLE
"No sessions found"

### ISSUE THREAD

**Issue by StonedEdge** [langest/RetroStats#2]
Hi there,

Sorry to bump an extremely old project, however I'd like to use this repository to display my game history on an OLED display I have working with a docking station I am currently building. Right now I have cloned the repository and ran retro-stats-cli -h (which works fine on the CLI) however when running an additional command like retro-stats-cli -c total, I get:

`
No sessions found
`

Any idea why this may be? I have played one single game (just as a test for 30 seconds) - is there a minimum duration of playtime equired before this command will work? I will not be using the server function of this repository. 

Thank you!

**Comment by langest** [comment]
As you closed this, you probably found the answer by yourself. I'll leave this in case someone else come across this.

Yes, there is a minimum length.
```
    parser.add_argument(
        "-m",
        "--minimum-session-length",
        type=int,
        default=120,
        help="skip sessions shorter than this number of seconds, defaults to 120",
    )
```
